### PR TITLE
New build scripts for mtpass.

### PR DESCRIPTION
**Pull request by zaninime**

### CODE REVIEW

**Comment by manio** [comment]
Thank you, but could you please adjust it a little?
1. If we're doing this change, then I'd like to move source files to 'src' subdirectory first, so the first commit in PR should be with file movement. Then in Makefile.am please add:
SUBDIRS = src, and please adjust the rest of files accordingly.
2. I am not planning to store generated scripts in the git repository, I only need minimal files to generate them (your bootstrap.sh is fine here). Generated scripts will be in the tarball, which I am providing on homepage.
3. It seems that configure.in is not included.

regards

**Comment by zaninime** [comment]
1. You can accept the pull request, then do the corrections you want.
2. Just remove them.
3. configure.in is not necessary, you just need configure.ac.

2013/12/2 Mariusz Białończyk notifications@github.com

> Thank you, but could you please adjust it a little?
> 1. If we're doing this change, then I'd like to move source files to 'src'
> subdirectory first, so the first commit in PR should be with file movement.
> Then in Makefile.am please add:
> SUBDIRS = src, and please adjust the rest of files accordingly.
> 2. I am not planning to store generated scripts in the git repository, I
> only need minimal files to generate them (your bootstrap.sh is fine here).
> Generated scripts will be in the tarball, which I am providing on homepage.
> 3. It seems that configure.in is not included.
> 
> regards
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/manio/mtpass/pull/1#issuecomment-29635357
> .

## 

Francesco Zanini

**Comment by manio** [comment]
Ok, I'll cherry-pick and/or rebase your changes when I have time...

**Comment by manio** [comment]
Merged! I'll move sources to src subdir and create a tarball with generated scripts when I find some time.
Thank you for your work!

**Pull request closed without merging**
